### ISSUE TITLE
修改模型

### ISSUE THREAD

**Issue by beita6969** [DinorexTim/GPT-webUI#2]
你好，很棒的项目，请问在哪里可以修改调用的模型呢，我想调用gpt-4o的模型，应该在哪里做出修改呢

**Comment by DinorexTim** [comment]
`public/chat.html`增添`<a href="#" onclick="selectModel('GPT-4o')">GPT-4-turbo</a>`即可

![](https://github.com/user-attachments/assets/811f6d85-d791-47bc-b867-d58a0b9da1cc)
